#!/usr/bin/env bash

kubectl apply -f blue_deployment.yaml

kubectl rollout status deployment/django-blue

# Test availability
while true; do
  curl http://localhost || true
  sleep 2
done &

sleep 10
kill %1 || true

kubectl get pods
